# Generated by Django 5.1.6 on 2025-02-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adrecord',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='ad_id',
            field=models.CharField(help_text='Unique identifier for the ad', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='timestamp',
            field=models.DateTimeField(help_text='Date and time when the ad was played'),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='total_persons',
            field=models.IntegerField(help_text='Total persons detected'),
        ),
        migrations.AlterModelTable(
            name='adrecord',
            table='ad_record',
        ),
        migrations.CreateModel(
            name='AdAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(help_text='Unique person ID within the context of an ad')),
                ('counted', models.BooleanField(help_text='Whether this person was counted')),
                ('age', models.IntegerField(blank=True, help_text='Age of the person', null=True)),
                ('gender', models.CharField(blank=True, help_text='Gender of the person', max_length=10, null=True)),
                ('ad_record', models.ForeignKey(help_text='Ad record to which this person belongs', on_delete=django.db.models.deletion.CASCADE, related_name='ad_analytics', to='analytics.adrecord')),
            ],
            options={
                'db_table': 'ad_analytics',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
